#pragma once

/**********************************************/
/*  Standards supported for FIRecord
***********************************************/
typedef enum tagLUMI_FIR_STANDARD 
{ 
	FIR_ISO		= 0, // ISO/IEC 19794-4:2005
	FIR_ANSI	= 1 // ANSI/INCITS 381-2004
} LUMI_FIR_STANDARD;

/**********************************************/
/*  Compression Algorithm Codes 
***********************************************/
typedef enum tagLUMI_COMPRESSION_TYPE 
{ 
	UNCOMPRESSED_NO_BIT_PACKING		= 0, 
	UNCOMPRESSED_BIT_PACKED			= 1, 
	COMPRESSED_WSQ					= 2, 
	COMPRESSED_JPEG					= 3, 
	COMPRESSED_JPEG2000				= 4, 
	COMPRESSED_PNG					= 5
} LUMI_COMPRESSION_TYPE;

/**********************************************/
/*  Finger/Palm Position Codes
***********************************************/
typedef enum  tagLUMI_FINGER_PALM_POSITION
{
	FINGER_POSITION_UNKNOWN_FINGER				= 0,
	FINGER_POSITION_RIGHT_THUMB					= 1,
	FINGER_POSITION_RIGHT_INDEX_FINGER			= 2,
	FINGER_POSITION_RIGHT_MIDDLE_FINGER			= 3,
	FINGER_POSITION_RIGHT_RING_FINGER			= 4,
	FINGER_POSITION_RIGHT_LITTLE_FINGER			= 5,
	FINGER_POSITION_LEFT_THUMB					= 6,
	FINGER_POSITION_LEFT_INDEX_FINGER			= 7,
	FINGER_POSITION_LEFT_MIDDLE_FINGER			= 8,
	FINGER_POSITION_LEFT_RING_FINGER			= 9,
	FINGER_POSITION_LEFT_LITTLE_FINGER			= 10,
	FINGER_POSITION_PLAIN_RIGHT_FOUR_FINGERS	= 13,
	FINGER_POSITION_PLAIN_LEFT_FOUR_FINGERS		= 14,
	FINGER_POSITION_PLAIN_THUMBS				= 15,
	PALM_POSITION_UNKNOWN_PALM					= 20,
	PALM_POSITION_RIGHT_FULL_PALM				= 21,
	PALM_POSITION_RIGHT_WRITERS_PALM			= 22,
	PALM_POSITION_LEFT_FULL_PALM				= 23,
	PALM_POSITION_LEFT_WRITERS_PALM				= 24,
	PALM_POSITION_RIGHT_LOWER_PALM				= 25,
	PALM_POSITION_RIGHT_UPPER_PALM				= 26,
	PALM_POSITION_LEFT_LOWER_PALM				= 27,
	PALM_POSITION_LEFT_UPPER_PALM				= 28,
	PALM_POSITION_RIGHT_OTHER					= 29,
	PALM_POSITION_LEFT_OTHER					= 30,
	PALM_POSITION_RIGHT_INTERDIGITAL			= 31,
	PALM_POSITION_RIGHT_THENAR					= 32,
	PALM_POSITION_RIGHT_HYPOTHENAR				= 33,
	PALM_POSITION_LEFT_INTERDIGITAL				= 34,
	PALM_POSITION_LEFT_THENAR					= 35,
	PALM_POSITION_LEFT_HYPOTHENAR				= 36
} LUMI_FINGER_PALM_POSITION;

/**********************************************/
/*  Impression Types
***********************************************/
typedef enum  tagLUMI_IMPRESSION_TYPE
{
	LIVE_SCAN_PLAIN			= 0,
	LIVE_SCAN_ROLLED		= 1,
	NONLIVE_SCAN_PLAIN		= 2,
	NONLIVE_SCAN_ROLLED		= 3,
	LATENT					= 7,		
	SWIPE					= 8,
	LIVE_SCAN_CONTACTLESS	= 9
}LUMI_IMPRESSION_TYPE;


